steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/svc-texture', '.']
images: ['gcr.io/$PROJECT_ID/svc-texture']

timeout: 13000s
options:
  machineType: 'N1_HIGHCPU_32'